# Generated by Django 5.0 on 2024-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(),
        ),
    ]
